### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by txj-xyz** [txj-xyz/pvme-util-bot#1]
- [x] Add options to pick the role for `/mastery role:ROLE_MENTION_HERE` mastery
- [x] Add stats for most contributing member on `pvme/pvme-guides`
- [x] Convert to `new SlashCommandBuilder()` method for interactions
- [x] Add global method support instead of `UtilityHandler.ts` since we are now on `ESNext` syntax
